version: "3"

services:
  vote:
    build: ./vote
    networks:
      - back-tier

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  lb_vote:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - vote
    networks:
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-data:

networks:
  back-tier:
    ipam:
      config:
      - subnet: 172.26.0.0/24
