version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    # volumes:
    # - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - back-tier

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier:
    ipam:
      config:
      - subnet: 172.26.0.0/24
